#Creating files with dynamic content
#================================================================
#Scenario: Write an Ansible Playbook to create a file called as Readme.txt
           #with the following content
#================================================================
#Hello,
#This file is created using Ansible Automation.
#The operating system family = <>
#Operating system = <>
#================================================================
#For this we would be using Jinja2 templates in Ansible Refer Here
#and also over here
#================================================================
#Create a file called as readme.txt.j2 with following content
#================================================================
#This file is created using Ansible Automation.

#The operating system family = {{ ansible_os_family }}

#Operating system = {{ ansible_distribution }} {{ ansible_distribution_version }}

#Thanks from {{ test_user }}

#Now create a playbook with the following content
#================================================================
---
- hosts: all
  vars:
    test_user: devops team
  tasks:
    - name: copy the template with dynamic
      template:
        src: readme.txt.j2
        dest: /home/devops/readme.txt