---
- hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
    - name: install httpd
      yum: 
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
      - name: enable apache2
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "Redhat" 